version: "3.3"
services:
  db:
    container_name: dionisio_db
    env_file: .env
    restart: always
    image: postgres:alpine
    ports: 
      - ${POSTGRES_PORT}:5432
      
  api:
    container_name: dionisio_api
    env_file: .env
    restart: always
    network_mode: "host"
    depends_on:
      - "db"
    build: .
    volumes:
      - .:/usr/
    ports:
      - ${PORT}:${PORT}

